### ISSUE TITLE
Almost/All ros wiki mirror sites are outdated

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/mirror#20]
- I see the status command on wiki shows all mirrors are outdated.
   ![Screenshot from 2021-03-31 13-07-07](https://user-images.githubusercontent.com/1840401/113183441-0841b780-9222-11eb-9a13-7b6d887ea315.png)
- Some people were wondering back in July 2020 [answers.ros.org#q356931](https://answers.ros.org/question/356931/wiki-mirror-missing-wiki-pages/).
- Today I saw roswiki was down in early morning in ET, so wanted to count on mirrors. However, for example for `actionlib_tutorials/Tutorials/Writing a Simple Action Server using the Execute Callback (Python)`, these sites show "2021-03-27 12:28" and no actual contents.
   - http://mirror.umd.edu/roswiki/actionlib_tutorials(2f)Tutorials(2f)Writing(20)a(20)Simple(20)Action(20)Server(20)using(20)the(20)Execute(20)Callback(2028)Python(29).html
      - For UMD, http://mirror.umd.edu/roswiki/actionlib(2f)DetailedDescription.html appears meaningful though.
   - http://mirror-eu.wiki.ros.org/actionlib_tutorials(2f)Tutorials(2f)SimpleActionServer(28)ExecuteCallbackMethod(29).html
   - http://wiki.ros.org.jsk.imi.i.u-tokyo.ac.jp/actionlib_tutorials(2f)Tutorials(2f)Writing(20)a(20)Simple(20)Action(20)Server(20)using(20)the(20)Execute(20)Callback(2028)Python(29).html
      ![Screenshot from 2021-03-31 13-12-11](https://user-images.githubusercontent.com/1840401/113184131-d0873f80-9222-11eb-8c2d-65b3238839dd.png)

**Comment by tfoote** [comment]
Unfortunately the javascript logic reports outdated if the target mirror is http not https. Due to browser security policies we can't fetch non-https content embedded in a https website. My current viewing is that only one mirror is https and pollable right now. But clicking on them more are up to date but need manual verification. 

Contributions to improve the detection would be welcome in the roswiki Macro. 

https://github.com/ros-infrastructure/roswiki/blob/master/macro/MirrorStatus.py

https://github.com/ros-infrastructure/roswiki/blob/master/custom/js/mirrorstatus.js and
